[aws]
AWS_ACCESS_KEY_ID = "AKIA47CRYSWPLHXWDH4B"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "eu-west-1"

[mlflow]
MLFLOW_TRACKING_URI = "http://ec2-52-209-5-80.eu-west-1.compute.amazonaws.com:5000"